const fs = require('fs');
let content = fs.readFileSync('Liverton-learning/src/pages/HannaChat.tsx', 'utf8');

content = content.replace(
  "                messages.map((message) => (\n                  <div\n                    key={message.id}\n                    className={`flex ${\n                      message.senderRole === 'user'\n                        ? 'justify-end'\n                        : 'justify-start'\n                    } group`}\n                  >\n                    <div\n                      className={`max-w-md lg:max-w-2xl ${\n                        message.senderRole === 'user'\n                          ? 'order-2'\n                          : 'order-1'\n                      }`}\n                    >\n                      <Card\n                        className={`p-4 rounded-2xl transition-all ${\n                          message.senderRole === 'user'\n                            ? 'bg-gradient-to-br from-purple-600 to-purple-700 text-white dark:from-purple-700 dark:to-purple-800 shadow-lg'\n                            : 'bg-white dark:bg-gray-800 text-black dark:text-white border border-gray-200 dark:border-gray-700'\n                        }`}\n                      >\n                        <p className=\"text-xs font-semibold mb-2 opacity-75\">\n                          {message.senderName}\n                        </p>\n                        <p className=\"text-sm leading-relaxed whitespace-pre-wrap\">\n                          {message.content}\n                        </p>\n                        <p className=\"text-xs opacity-60 mt-2\">\n                          {formatTime(message.createdAt)}\n                        </p>\n                      </Card>\n                      {message.senderRole === 'hanna' && (\n                        <div className=\"flex items-center gap-2 mt-2 opacity-0 group-hover:opacity-100 transition-opacity\">\n                          <Button\n                            variant=\"ghost\"\n                            size=\"sm\"\n                            onClick={() => handleCopyMessage(message.content)}\n                            className=\"h-8 px-2 text-xs text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200\"\n                          >\n                            <Copy className=\"w-3 h-3 mr-1\" />\n                            Copy\n                          </Button>\n                        </div>\n                      )}\n                    </div>\n                  </div>\n                ))",
  "                messages.map((message) => (\n                  <ChatMessage\n                    key={message.id}\n                    message={message}\n                    isCurrentUser={message.senderRole === 'user'}\n                    showDate={false}\n                    customColors={chatSettings.colors}\n                    fontSize={chatSettings.fontSize}\n                    fontStyle={chatSettings.fontStyle}\n                    isRecipientOnline={true}\n                    isMessageRead={true}\n                    onDelete={handleDeleteMessage}\n                    onEdit={handleEditMessage}\n                  />\n                ))"
);

fs.writeFileSync('Liverton-learning/src/pages/HannaChat.tsx', content);
