import { ArrowRight, CheckCircle2, CircleDollarSign, Clock3, Heart, Plus, Sparkles, Target, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import AuthenticatedLayout from '@/components/AuthenticatedLayout';

const campaigns = [
  { title: 'STEM kits for rural classrooms', owner: 'Bright Future School', raised: '$8,420', goal: '$12,000', progress: 70, tag: 'Education access', color: '#c9f36b' },
  { title: 'Build the Liverton robotics lab', owner: 'Amina K. · Educator', raised: '$4,860', goal: '$7,500', progress: 64, tag: 'Project launch', color: '#bca7ff' },
  { title: 'Community reading rooms', owner: 'Northside Learning Hub', raised: '$2,140', goal: '$3,000', progress: 71, tag: 'Community', color: '#8de5dc' },
];

export default function LiveFund() {
  const navigate = useNavigate();
  return <AuthenticatedLayout><div className="lf-page"><header className="lf-header"><div><span className="lp-overline">Grow ideas</span><h1>LivFund</h1><p>Go get funded for the work that moves learning forward.</p></div><button className="lf-primary" onClick={() => navigate('/features/liv-fund/create')}><Plus size={16} /> Start a campaign</button></header><section className="lf-hero"><div><span className="lf-kicker"><Sparkles size={14} /> Funding with purpose</span><h2>Make your next<br /><em>good idea happen.</em></h2><p>Connect projects with supporters, track progress, and turn completed work into opportunities on LivMart.</p><button className="lf-dark" onClick={() => document.getElementById('campaigns')?.scrollIntoView({ behavior: 'smooth' })}>Explore campaigns <ArrowRight size={16} /></button></div><div className="lf-hero-stat"><CircleDollarSign size={26} /><strong>$124k</strong><span>raised by the community</span><div className="lf-sparkline"><i /><i /><i /><i /><i /><i /><i /></div></div></section><div className="lf-stats"><div><Target size={18} /><strong>48</strong><span>active projects</span></div><div><Users size={18} /><strong>1,284</strong><span>supporters</span></div><div><CheckCircle2 size={18} /><strong>76%</strong><span>success rate</span></div><div><Clock3 size={18} /><strong>12 days</strong><span>average to fund</span></div></div><section id="campaigns" className="lf-list"><div className="lf-list-heading"><div><span className="lp-overline">Find your next yes</span><h2>Projects worth backing</h2></div><button>View all <ArrowRight size={15} /></button></div><div className="lf-grid">{campaigns.map((campaign) => <article className="lf-card" key={campaign.title}><div className="lf-card-art" style={{ background: `linear-gradient(135deg, ${campaign.color}, #fff)` }}><span>{campaign.tag}</span><Heart size={18} /></div><div className="lf-card-body"><small>{campaign.owner}</small><h3>{campaign.title}</h3><div className="lf-progress"><i style={{ width: `${campaign.progress}%` }} /></div><div className="lf-money"><strong>{campaign.raised}</strong><span>of {campaign.goal}</span><b>{campaign.progress}%</b></div><button>View project <ArrowRight size={14} /></button></div></article>)}</div></section></div></AuthenticatedLayout>;
}
