import { ArrowLeft, BookOpen } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { SEO } from '@/components/SEO';

export default function TermsOfService() {
  const navigate = useNavigate();
  return <><SEO title="Terms of Service" description="Liverton Learning terms of service." noIndex /><main className="min-h-screen bg-background px-4 py-6 text-foreground"><div className="mx-auto max-w-3xl"><Button variant="ghost" className="mb-8 rounded-xl" onClick={() => navigate(-1)}><ArrowLeft className="mr-2 h-4 w-4" /> Back to workspace</Button><div className="mb-8 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-black dark:bg-white"><BookOpen className="h-5 w-5 text-white dark:text-black" /></div><div><p className="text-sm text-muted-foreground">Liverton Learning</p><h1 className="text-3xl font-bold">Terms of Service</h1></div></div><article className="prose prose-slate max-w-none dark:prose-invert"><p className="lead">These terms describe the expectations for using Liverton Learning, its education tools, collaboration spaces, documents, marketplace features, funding features, and Hanna AI.</p><h2>Using Liverton responsibly</h2><p>Use Liverton for lawful learning, teaching, collaboration, and organization activities. Keep your account credentials private, provide accurate profile information, and do not attempt to access records or workspaces that you are not authorized to use.</p><h2>Content and permissions</h2><p>You retain responsibility for the content you upload, create, share, submit, or publish. Only share documents, images, lessons, project materials, and personal information with people who are authorized to receive them.</p><h2>Hanna AI</h2><p>Hanna provides assistance, suggestions, summaries, research, and drafting support. Review important outputs before relying on them, and confirm any external, financial, publishing, submission, or irreversible action before it is performed.</p><h2>Platform changes</h2><p>Liverton may improve, change, or retire features as the platform develops. Current feature availability depends on your role, permissions, organization, and account status.</p><h2>Contact and updates</h2><p>For account or platform questions, use the in-app support entry or contact your organization administrator. The latest version of these terms is the version presented on this page.</p></article></div></main></>;
}
