import { useNavigate } from 'react-router-dom';
import { ArrowUpRight, BarChart3, BookOpen, CheckCircle2, ChevronRight, Clock3, Flame, Play, Star, Target, Users } from 'lucide-react';

const continueLearning = [
  { title: 'Design thinking for young creators', lesson: 'Lesson 5 · Finding better questions', progress: 68, color: '#b7f36b' },
  { title: 'Everyday financial literacy', lesson: 'Lesson 3 · Saving with intention', progress: 42, color: '#c8b8ff' },
];

export default function StudentDashboard() {
  const navigate = useNavigate();
  return <div className="liv-page">
    <header className="liv-page-header"><div><span className="liv-eyebrow">Student space · Your learning rhythm</span><h1 className="liv-title">Keep going, Sam.</h1><p className="liv-subtitle">You are building a strong week. One focused lesson today keeps your momentum alive.</p></div><button className="liv-button liv-button-green" onClick={() => navigate('/student/courses')}><BookOpen size={16} /> Explore modules</button></header>
    <section className="liv-hero-card"><div><span className="liv-eyebrow">Your streak</span><h2>4 days of showing up.</h2><p>Small steps compound. Finish one lesson before your next team session and keep your streak glowing.</p><button className="liv-button liv-button-green" style={{ marginTop: 20 }} onClick={() => navigate('/student/courses')}>Continue learning <ArrowUpRight size={15} /></button></div><div style={{ display: 'grid', placeItems: 'center', minWidth: 90 }}><Flame size={58} color="var(--liv-green)" fill="var(--liv-green)" /></div></section>
    <div className="liv-grid-4" style={{ marginTop: 14 }}>{[['Current streak', '4 days', 'Best: 9 days', Flame], ['Learning time', '3h 42m', 'This week', Clock3], ['Completed', '18 lessons', '+4 this month', CheckCircle2], ['Goals', '72%', 'On track', Target]].map(([label, value, note, Icon]) => <div className="liv-card liv-stat" key={String(label)}><div className="liv-stat-top"><span>{label}</span><span className="liv-stat-icon"><Icon size={16} /></span></div><strong className="liv-stat-value">{value}</strong><span className="liv-stat-note">{note}</span></div>)}</div>
    <div className="liv-section-head"><h2>Continue learning</h2><button onClick={() => navigate('/student/courses')}>My library <ChevronRight size={14} style={{ verticalAlign: '-3px' }} /></button></div>
    <div className="liv-grid-2">{continueLearning.map((item) => <article className="liv-card" key={item.title}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><span className="liv-chip">In progress</span><button className="liv-button liv-button-green" style={{ width: 38, height: 38, padding: 0, justifyContent: 'center' }} aria-label="Play lesson"><Play size={15} fill="currentColor" /></button></div><h3 style={{ fontFamily: 'Space Grotesk', fontSize: 20, letterSpacing: '-.05em', margin: '21px 0 7px' }}>{item.title}</h3><p style={{ color: 'var(--liv-muted)', fontSize: 12, margin: 0 }}>{item.lesson}</p><div style={{ marginTop: 22 }}><div className="liv-inline-label"><span>{item.progress}% complete</span><strong>Next up</strong></div><div className="liv-progress"><span style={{ width: `${item.progress}%`, background: item.color }} /></div></div></article>)}</div>
    <div className="liv-section-head"><h2>Recommended for you</h2><span className="liv-eyebrow">Based on your interests</span></div>
    <div className="liv-grid-3">{['Build your first portfolio', 'Creative coding basics', 'Speak with confidence'].map((title, i) => <article className="liv-card" key={title}><span className="liv-chip is-selected">{i === 0 ? 'Popular' : 'New'}</span><h3 style={{ fontFamily: 'Space Grotesk', fontSize: 18, letterSpacing: '-.04em', margin: '18px 0 7px' }}>{title}</h3><p style={{ color: 'var(--liv-muted)', fontSize: 11, margin: 0 }}>{['10 lessons · 4.7 rating', '7 lessons · 4.9 rating', '5 lessons · 4.8 rating'][i]}</p><div style={{ display: 'flex', alignItems: 'center', gap: 5, marginTop: 17 }}><Star size={13} fill="#b87819" color="#b87819" /><span style={{ fontSize: 12, fontWeight: 700 }}>{['4.7', '4.9', '4.8'][i]}</span><span style={{ color: '#9ba097', fontSize: 11 }}>from learners</span></div><button className="liv-button liv-button-light" style={{ marginTop: 18, width: '100%', justifyContent: 'center' }} onClick={() => navigate('/student/courses')}>View module <ArrowUpRight size={14} /></button></article>)}</div>
    <div className="liv-section-head"><h2>Teams & community</h2><button onClick={() => navigate('/features/liv-teams')}>Open Liv Teams</button></div>
    <div className="liv-card" style={{ display: 'flex', alignItems: 'center', gap: 14 }}><span className="liv-row-icon" style={{ width: 42, height: 42, background: '#ece7ff', display: 'grid', placeItems: 'center', borderRadius: 13 }}><Users size={18} /></span><div><h3 style={{ margin: 0, fontSize: 14 }}>Portfolio builders circle</h3><p style={{ margin: '4px 0 0', color: 'var(--liv-muted)', fontSize: 11 }}>3 new messages · Project checkpoint tomorrow</p></div><button className="liv-button liv-button-light" style={{ marginLeft: 'auto' }} onClick={() => navigate('/features/liv-teams')}>View <ChevronRight size={14} /></button></div>
  </div>;
}
